[project]
name = "benchmarks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "rich>=14.1.0",
    "torch>=2.8.0",
    "typer>=0.17.4",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
